"""create all tables

Revision ID: 0c847fe2969a
Revises: 
Create Date: 2026-06-27 14:20:31.491634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c847fe2969a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'PATIENT', 'MODERATOR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('job_position', sa.String(length=200), nullable=True),
    sa.Column('job_place', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ATTACHED', 'DETACHED', name='patientstatus', native_enum=False), nullable=False),
    sa.Column('surname_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=False),
    sa.Column('sex', sa.Enum('M', 'F', name='sextype', native_enum=False), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('birth_year', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('height', sa.SmallInteger(), nullable=True),
    sa.Column('disability', sa.Enum('GROUP_1', 'GROUP_2', 'GROUP_3', 'NONE', name='disabilitygroup', native_enum=False), nullable=False),
    sa.Column('diagnosis', sa.Enum('UC', 'CD', 'UNCLASSIFIED', name='diagnosistype', native_enum=False), nullable=False),
    sa.Column('histologically_confirmed', sa.Enum('YES', 'NO', 'UNKNOWN', name='histologystatus', native_enum=False), nullable=False),
    sa.Column('diagnosis_year', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('birth_year BETWEEN 1900 AND 2100', name='chk_birth_year'),
    sa.CheckConstraint('height > 0', name='chk_height'),
    sa.CheckConstraint('weight > 0', name='chk_weight'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('patient_self_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assessment_type', sa.Enum('CD', 'UC', name='assessmenttype', native_enum=False), nullable=False),
    sa.Column('cd_abdominal_pain', sa.SmallInteger(), nullable=True),
    sa.Column('cd_stool_count', sa.SmallInteger(), nullable=True),
    sa.Column('uc_rectal_bleeding', sa.SmallInteger(), nullable=True),
    sa.Column('uc_defecation_freq', sa.SmallInteger(), nullable=True),
    sa.Column('pro2_score', sa.SmallInteger(), nullable=True),
    sa.Column('first_symptoms_date', sa.Date(), nullable=True),
    sa.Column('first_symptoms_desc', sa.Text(), nullable=True),
    sa.Column('possible_factors', sa.Text(), nullable=True),
    sa.Column('constipation_on_flare', sa.Boolean(), nullable=True),
    sa.Column('constipation_stool_freq', sa.Text(), nullable=True),
    sa.Column('filled_by_patient', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_assessment_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('state_records_cd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('localization', sa.String(length=2), nullable=True),
    sa.Column('perianal_lesions', sa.Boolean(), nullable=True),
    sa.Column('behavior', sa.String(length=2), nullable=True),
    sa.Column('general_wellbeing', sa.SmallInteger(), nullable=True),
    sa.Column('abdominal_pain', sa.SmallInteger(), nullable=True),
    sa.Column('stool_count', sa.SmallInteger(), nullable=True),
    sa.Column('abdominal_mass', sa.SmallInteger(), nullable=True),
    sa.Column('ses_cd', sa.String(length=10), nullable=True),
    sa.Column('ses_cd_other', sa.String(length=200), nullable=True),
    sa.Column('harvey_bradshaw', sa.SmallInteger(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_records_clinical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('strictures', sa.Boolean(), nullable=True),
    sa.Column('penetrations_fistulas', sa.Boolean(), nullable=True),
    sa.Column('fecal_incontinence', sa.String(length=10), nullable=True),
    sa.Column('infectious_complications', sa.Text(), nullable=True),
    sa.Column('abdominal_surgeries', sa.Boolean(), nullable=True),
    sa.Column('steroid_dependence', sa.Boolean(), nullable=True),
    sa.Column('steroid_resistance', sa.Boolean(), nullable=True),
    sa.Column('advanced_therapy_resistance', sa.Boolean(), nullable=True),
    sa.Column('smoking_status', sa.Enum('CURRENT', 'NEVER', 'FORMER', name='smokingstatus', native_enum=False), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('resistant_drugs_other', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_records_uc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extent', sa.String(length=2), nullable=True),
    sa.Column('stool_frequency', sa.SmallInteger(), nullable=True),
    sa.Column('rectal_bleeding', sa.SmallInteger(), nullable=True),
    sa.Column('physician_assessment', sa.SmallInteger(), nullable=True),
    sa.Column('endoscopic_mayo', sa.SmallInteger(), nullable=True),
    sa.Column('endoscopic_mayo_other', sa.String(length=200), nullable=True),
    sa.Column('partial_mayo', sa.SmallInteger(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cd_complications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('complication', sa.Enum('ARTHRALGIA', 'UVEITIS', 'ERYTHEMA_NODOSUM', 'APHTHOUS_ULCERS', 'PYODERMA', 'ANAL_FISSURE', 'NEW_FISTULA', 'ABSCESS', name='cdcomplicationtype', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['state_records_cd.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'complication')
    )
    op.create_table('clinical_lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('lab_type', sa.Enum('CRP', 'CALPROTECTIN', name='labtype', native_enum=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('result_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['state_records_clinical.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_resistant_drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('drug', sa.Enum('INFLIXIMAB', 'ADALIMUMAB', 'VEDOLIZUMAB', 'USTEKINUMAB', 'TOFACITINIB', 'UPADACITINIB', 'OTHER', name='resistantdrugtype', native_enum=False), nullable=False),
    sa.Column('other_drug_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['state_records_clinical.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'drug')
    )
    op.create_table('clinical_surgeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['state_records_clinical.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('drug', sa.Enum('ASA_5', 'BUDESONIDE', 'SYSTEMIC_STEROIDS', 'THIOPURINES', 'METHOTREXATE', 'ANTI_TNF', 'VEDOLIZUMAB', 'USTEKINUMAB', 'TOFACITINIB', 'UPADACITINIB', 'OTHER', name='drugtype', native_enum=False), nullable=False),
    sa.Column('other_drug_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['state_records_clinical.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_treatments')
    op.drop_table('clinical_surgeries')
    op.drop_table('clinical_resistant_drugs')
    op.drop_table('clinical_lab_results')
    op.drop_table('cd_complications')
    op.drop_table('state_records_uc')
    op.drop_table('state_records_clinical')
    op.drop_table('state_records_cd')
    op.drop_table('self_assessment_tokens')
    op.drop_table('patient_self_assessments')
    op.drop_table('auth_tokens')
    op.drop_table('patient_profiles')
    op.drop_table('users')
    op.drop_table('regions')
    # ### end Alembic commands ###
